---
- name: Deploy HTML Application
  hosts: webservers
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Clone the DevOps-course repository
      ansible.builtin.git:
        repo: 'https://github.com/mateja81/DevOps-course.git'
        dest: /tmp/DevOps-course
        version: main

    - name: Copy HTML file to the web server directory
      copy:
        src: /tmp/DevOps-course/index.html
        dest: /var/www/html/index.html

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
