---
- name: Deploy HTML Application
  hosts: webservers
  become: true

  tasks:
    - name: Install Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Copy HTML files to the web server directory
      copy:
        src: /home/vagrant/html_files/
        dest: /var/www/html/

    - name: Start and enable Nginx service
      service:
        name: nginx
        state: started
        enabled: yes
