---
- name: Deploy Docker Web Server and Ensure Webpage Updates
  hosts: localhost
  tasks:
    - name: Pull Nginx Docker Image
      community.docker.docker_image:
        name: nginx
        source: pull

    - name: Run Nginx container with bind mount for HTML directory
      community.docker.docker_container:
        name: nginx_webserver
        image: nginx
        state: started
        ports:
          - "8080:80"
        volumes:
          - "/home/vagrant/html:/usr/share/nginx/html"

    - name: Ensure the container is running
      community.docker.docker_container_info:
        name: nginx_webserver
      register: container_info

